version: '3.8'

services:
  sound-source:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    depends_on:
      - mongo_container
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI} # Load from .env file
    networks:
      - app-network
    command: npm run dev # Ensure this matches your app's start command
    restart: always

  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sound_source
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
