version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:example@mongo_container:27017/sound_source
    networks:
      - app-network
    command: npm run dev # 根据实际需求替换为应用的启动命令

  db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--tlsMode", "allowTLS"] # 替换 sslMode 为 tlsMode，解决 MongoDB 警告
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sound_source
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
